# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: Jarrod Davis
email: developer@jarrodldavis.com
title: >-
  Software engineer, scripting specialist, and full stack web developer
repository: jarrodldavis/jarrodldavis.github.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# SEO
twitter:
  username: ahylianhuman
  card: summary
social:
  name: Jarrod Davis
  links:
    - https://github.com/jarrodldavis
    - https://www.linkedin.com/in/jarrodldavis
    - https://www.twitter.com/ahylianhuman
    - https://www.upwork.com/fl/jarrodldavis

# Modern Resume Theme
about_profile_image: assets/me.jpg
about_content: |
  Hey! I'm Jarrod Davis, a full stack developer and software engineer who
  enjoys building delightful experiences and helpful tools. I've worked with
  numerous languages, frameworks, and libraries, with a significant focus on
  command-line utilities and web applications (frontend and backend).

  Here's a sampling of the technologies I've worked with:

  - A "traditional" Microsoft web stack ([C#][csharp], [.NET Framework][netfx],
    [ASP.NET MVC][aspnet])
  - The modern Microsoft web stack ([C#][csharp], [.NET Core][dotnet-core],
    [ASP.NET Core][aspnet-core], [Entity Framework Core][ef-core])
  - [Node.js][nodejs] as a web application backend (including
    [Express.js][expressjs] and [Next.js][nextjs]) and serverless function
    runtime
  - Component-based JavaScript frameworks (including [Vue.js][vuejs],
    [Angular][angular], and [React.js][reactjs])
  - Modern frontend build setups ([Babel][babeljs] and [webpack])
  - Several CSS preprocessors, including [Stylus][stylus], [Less][less], and
    [Sass/SCSS][sass]
  - [MySQL][mysql] query authoring and schema update management
  - [Node.js][nodejs], [Ruby], and [Python] for command-line scripts and utilities

  Below you can see more details of my professional and educational experience.
  You can also [download my resume as a PDF][resume]. If you have an
  interesting project to work on, [hire me on Upwork][upwork].

  [csharp]:       https://docs.microsoft.com/en-us/dotnet/csharp
  [netfx]:        https://docs.microsoft.com/en-us/dotnet/framework
  [aspnet]:       https://github.com/aspnet/AspNetWebStack
  [dotnet-core]:  https://github.com/dotnet/core
  [aspnet-core]:  https://github.com/aspnet/AspNetCore
  [ef-core]:      https://github.com/aspnet/EntityFrameworkCore
  [nodejs]:       https://nodejs.org
  [expressjs]:    https://expressjs.com
  [nextjs]:       https://nextjs.com
  [vuejs]:        https://vuejs.org
  [reactjs]:      https://reactjs.org
  [angular]:      https://angular.io
  [babeljs]:      https://babeljs.io
  [webpack]:      https://webpack.js.org
  [stylus]:       http://stylus-lang.com
  [less]:         http://lesscss.org
  [sass]:         https://sass-lang.com
  [mysql]:        https://www.mysql.com
  [ruby]:         https://www.ruby-lang.org
  [python]:       https://python.org
  [resume]:       /jarrod-davis-resume.pdf
  [upwork]:       https://www.upwork.com/fl/jarrodldavis

twitter_username: ahylianhuman
github_username:  jarrodldavis
linkedin_username:  jarrodldavis
additional_links:
- title: Upwork
  icon: fa fa-briefcase
  url: https://www.upwork.com/fl/jarrodldavis

darkmode: false # respect device preferences

# Build settings
markdown: kramdown
kramdown:
  auto_ids: false
  parse_block_html: true
remote_theme: sproogen/modern-resume-theme
plugins:
  - jekyll-feed
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
