# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jarrod Davis
email: developer@jarrodldavis.com
description: >- # this means to ignore newlines until "baseurl:"
  Full stack web engineer with a passion for user experience.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# SEO
twitter:
  username: ahylianhuman
  card: summary
social:
  name: Jarrod Davis
  links:
    - https://github.com/jarrodldavis
    - https://www.linkedin.com/in/jarrodldavis
    - https://www.twitter.com/ahylianhuman
    - https://keybase.io/jarrodldavis

# Minima
twitter_username: ahylianhuman
github_username:  jarrodldavis
linkedin_username:  jarrodldavis

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
