overrides:
  '@ibm/telemetry-js': '-'
  'sass>@parcel/watcher': '-'
  'sass>chokidar': '-'
  'svelte-check>chokidar': '5'

allowBuilds:
  '@tailwindcss/oxide': true
  '@vercel/speed-insights': true
  'esbuild': true
  'sharp': true
  '@ibm/plex-mono': false
  '@ibm/plex-sans': false
  '@ibm/plex-serif': false

minimumReleaseAgeStrict: true
