overrides:
  'svelte-check>chokidar': '5'

allowBuilds:
  '@tailwindcss/oxide': true
  '@vercel/speed-insights': true
  'esbuild': true
  'sharp': true

minimumReleaseAgeStrict: true

peerDependencyRules:
  allowedVersions:
    '@csstools/media-query-list-parser@2.0.4>@csstools/css-parser-algorithms': '3.0.4'
    '@csstools/media-query-list-parser@2.0.4>@csstools/css-tokenizer': '3.0.3'
